kind: pipeline
name: default
 
steps:
- name: kaniko
  image: banzaicloud/drone-kaniko
  settings:
    repo: registry.kramergroup.science/workflows/get-cif-from-icsd
    registry: registry.kramergroup.science
